services:
  # A web service for the Django application
  - type: web
    name: healthcare-portal
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn healthcareportal.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: healthcare-portal
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: healthcare-portal-db
          property: connectionString

# A PostgreSQL database
databases:
  - name: healthcare-portal-db
    databaseName: healthcare_portal
    user: healthcare_portal
    plan: free
